#!/bin/sh

SSH_PID=$(/opt/bin/ps -o ppid= -p $$)
echo "${SSH_PID}: $(echo ${SSH_CLIENT} | tr ' ' '\n' | head -n1)" >> /tmp/sshd.pid
for ${PID} in $(cat /tmp/sshd.pid | grep -oE '[0-9]+:' | grep -oE '[0-9]+'); do
    kill -0 ${PID} || sed -i "/${PID}:/d" /tmp/sshd.pid
done
